// User page reducer constants
const SET_USER_PAGE_STATUS = "SET_USER_PAGE_STATUS";
const SET_USER_LOGGED_IN = "SET_USER_LOGGED_IN";

// Assigned tasks reducer constants
const SET_ASSIGNED_TASKS = "SET_ASSIGNED_TASKS";
const SET_ASSIGNED_TASKS_LOADING = "SET_ASSIGNED_TASKS_LOADING";

//Assignable tasks reducer constants
const SET_ASSIGNABLE_TASKS = "SET_ASSIGNABLE_TASKS";
const SET_ASSIGNABLE_TASKS_LOADING = "SET_ASSIGNABLE_TASKS_LOADING";

export {
  SET_USER_PAGE_STATUS,
  SET_USER_LOGGED_IN,
  SET_ASSIGNED_TASKS,
  SET_ASSIGNED_TASKS_LOADING,
  SET_ASSIGNABLE_TASKS,
  SET_ASSIGNABLE_TASKS_LOADING,
};
