// User page reducer constants
const SET_USER_PAGE_STATUS = "SET_USER_PAGE_STATUS";
const SET_USER_LOGGED_IN = "SET_USER_LOGGED_IN";

//
const SET_ASSIGNED_TASKS = "SET_ASSIGNED_TASKS";

export { SET_USER_PAGE_STATUS, SET_USER_LOGGED_IN, SET_ASSIGNED_TASKS };
