// User page reducer constants
const SET_USER_PAGE_STATUS = "SET_USER_PAGE_STATUS";
const SET_USER_LOGGED_IN = "SET_USER_LOGGED_IN";

// Assigned tasks reducer constants
const SET_ASSIGNED_TASKS = "SET_ASSIGNED_TASKS";
const SET_ASSIGNED_TASKS_LOADING = "SET_ASSIGNED_TASKS_LOADING";

//Assignable tasks reducer constants
const SET_ASSIGNABLE_TASKS = "SET_ASSIGNABLE_TASKS";
const SET_ASSIGNABLE_TASKS_LOADING = "SET_ASSIGNABLE_TASKS_LOADING";
const REMOVE_ASSIGNABLE_TASK = "REMOVE_ASSIGNABLE_TASK";

//User page task reducer constants
const SET_USER_PAGE_TASK_DATA = "SET_USER_PAGE_TASK_DATA";
const SET_USER_PAGE_TASK_LOADING = "SET_USER_PAGE_TASK_LOADING";
const UPDATE_USER_PAGE_TASK_DATA = "UPDATE_USER_PAGE_TASK_DATA";

//User page notifications reducer constants
const SET_USER_PAGE_NOTIFICATIONS_NEW_COMMENTS =
  "SET_USER_PAGE_NOTIFICATIONS_NEW_COMMENTS";
const CHANGE_USER_PAGE_NOTIFICATIONS_LOADING =
  "CHANGE_USER_PAGE_NOTIFICATIONS_LOADING";

// User page user reducer constants
const SET_USER_PAGE_USER_DATA = "SET_USER_PAGE_USER_DATA";
const SET_USER_PAGE_USER_LOADING = "SET_USER_PAGE_USER_LOADING";

// Custom feilds
const UPDATE_CUSTOM_FIELD_VALUE = "UPDATE_CUSTOM_FIELD_VALUE";

export {
  SET_USER_PAGE_STATUS,
  SET_USER_LOGGED_IN,
  SET_ASSIGNED_TASKS,
  SET_ASSIGNED_TASKS_LOADING,
  SET_ASSIGNABLE_TASKS,
  SET_ASSIGNABLE_TASKS_LOADING,
  REMOVE_ASSIGNABLE_TASK,
  SET_USER_PAGE_TASK_DATA,
  SET_USER_PAGE_TASK_LOADING,
  UPDATE_USER_PAGE_TASK_DATA,
  SET_USER_PAGE_NOTIFICATIONS_NEW_COMMENTS,
  CHANGE_USER_PAGE_NOTIFICATIONS_LOADING,
  SET_USER_PAGE_USER_DATA,
  SET_USER_PAGE_USER_LOADING,
  UPDATE_CUSTOM_FIELD_VALUE,
};
