//Pipeline reducer constants
const PIPELINE_SET_LOADING = "SET_LOADING";
const PIPELINE_SET_PIPELINE = "SET_PIPELINE";
const PIPELINE_MOVE_TASK = "MOVE_TASK";
const PIPELINE_REORDER_TASK = "REORDER_TASK";
const PIPELINE_ADD_TASK = "ADD_TASK";
const PIPELINE_ADD_STAGE = "ADD_STAGE";
const PIPELINE_DELETE_STAGE = "DELETE_STAGE";
const PIPELINE_SET_EXISTING_PIPELINES = "SET_EXISTING_PIPELINES";
const PIPELINE_ADD_EXISTING_PIPELINE = "ADD_EXISTING_PIPELINE";
const PIPELINE_EDIT_TASK = "EDIT_TASK";
const PIPELINE_EDIT_STAGE = "EDIT_STAGE";
const PIPELINE_MOVE_STAGE = "MOVE_STAGE";
const PIPELINE_ADD_PIPELINE = "ADD_PIPELINE";
const PIPELINE_EDIT_PIPELINE = "EDIT_PIPELINE";
const PIPELINE_SET_PRIMARY = "SET_PRIMARY";
const PIPELINES_SET = "SET_PIPELINES";
const PIPELINE_SET_PRIMARY2 = "SET_PRIMARY";
const PIPELINE_ADD_USER_TO_TASK = "ADD_USER_TO_TASK";
const PIPELINE_REMOVE_USER_FROM_TASK = "REMOVE_USER_FROM_TASK";
const PIPELINE_CHANGE_TASK_DONE_STATUS = "CHANGE_TASK_DONE_STATUS";
const PIPELINE_REMOVE_PIPELINE = "REMOVE_PIPELINE";
const PIPELINE_REMOVE_ACTIVE_PIPELINE = "REMOVE_ACTIVE_PIPELINE";
const PIPELINE_REMOVE_TASK = "REMOVE_TASK";
const PIPELINE_TOGGLE_VIEW = "TOGGLE_VIEW";
const PIPELINE_ADD_LABEL_TO_TASK = "ADD_LABEL_TO_TASK";
const PIPELINE_REMOVE_LABEL_FROM_TASK = "REMOVE_LABEL_FROM_TASK";
const PIPELINE_EDIT_LABEL = "EDIT_PIPELINE_LABEL";
const PIPELINE_REMOVE_LABEL = "REMOVE_PIPELINE_LABEL";
const PIPELINE_SET_TASK_FOCUS_COLOR = "SET_TASK_FOCUS_COLOR";

//Active pipeline task view reducer constants
const SET_STAGE_FILTER = "SET_STAGE_FILTER";
const SET_USER_FILTER = "SET_USER_FILTER";
const SET_TASK_VIEW_SEARCH_TEXT = "SET_TASK_VIEW_SEARCH_TEXT";

//Modal reducer constants
const OPEN_NEW_TASK_MODAL = "OPEN_NEW_TASK_MODAL";
const CLOSE_NEW_TASK_MODAL = "CLOSE_NEW_TASK_MODAL";
const OPEN_EDIT_TASK_MODAL = "OPEN_EDIT_TASK_MODAL";
const CLOSE_EDIT_TASK_MODAL = "CLOSE_EDIT_TASK_MODAL";
const CLOSE_TASK_MODAL = "CLOSE_TASK_MODAL";
const OPEN_NEW_STAGE_MODAL = "OPEN_NEW_STAGE_MODAL";
const CLOSE_STAGE_MODAL = "CLOSE_STAGE_MODAL";
const OPEN_STAGE_EDIT_MODAL = "OPEN_STAGE_EDIT_MODAL";
const OPEN_NEW_PIPELINE_MODAL = "OPEN_NEW_PIPELINE_MODAL";
const OPEN_EDIT_PIPELINE_MODAL = "OPEN_EDIT_PIPELINE_MODAL";
const CLOSE_PIPELINE_MODAL = "CLOSE_PIPELINE_EDIT_MODAL";
const CLOSE_USER_MODAL = "CLOSE_USER_MODAL";
const OPEN_NEW_USER_MODAL = "OPEN_NEW_USER_MODAL";
const OPEN_EDIT_USER_MODAL = "OPEN_EDIT_USER_MODAL";
const ADD_ASSIGNED_USER_TO_EDITING_TASK = "ADD_ASSIGNED_USER_TO_EDITING_TASK";
const REMOVE_ASSIGNED_USER_FROM_EDITING_TASK =
  "REMOVE_ASSIGNED_USER_FROM_EDITING_TASK";
const CHANGE_USER_SETTINGS_MODAL_OPEN = "CHANGE_USER_SETTINGS_MODAL_OPEN";
const CHANGE_TASK_DONE_STATUS = "CHANGE_TASK_DONE_STATUS";
const OPEN_MOVE_TASK_MODAL = "OPEN_MOVE_TASK_MODAL";
const CLOSE_MOVE_TASK_MODAL = "CLOSE_MOVE_TASK_MODAL";
const OPEN_TASK_COLOR_MODAL = "OPEN_TASK_COLOR_MODAL";
const CLOSE_TASK_COLOR_MODAL = "CLOSE_TASK_COLOR_MODAL";
const OPEN_TASK_EXPORT_MODAL = "OPEN_TASK_EXPORT_MODAL";
const CLOSE_TASK_EXPORT_MODAL = "CLOSE_TASK_EXPORT_MODAL";
const CHANGE_TASK_EXPORT_MODAL_METHOD = "CHANGE_TASK_EXPORT_MODAL_METHOD";
const OPEN_PIPELINE_IMPORT_MODAL = "OPEN_PIPELINE_IMPORT_MODAL";
const CLOSE_PIPELINE_IMPORT_MODAL = "CLOSE_PIPELINE_IMPORT_MODAL";
const OPEN_AUTOMATION_CREATOR_MODAL = "OPEN_AUTOMATION_CREATOR_MODAL";
const CLOSE_AUTOMATION_CREATOR_MODAL = "CLOSE_AUTOMATION_CREATOR_MODAL";
const OPEN_AUTOMATIONS_MODAL = "OPEN_AUTOMATIONS_MODAL";
const CLOSE_AUTOMATIONS_MODAL = "CLOSE_AUTOMATIONS_MODAL";
const ARCHIVE_SETTINGS_MODAL_OPEN = "ARCHIVE_SETTINGS_MODAL_OPEN";
const OPEN_TASK_RESTORE_MODAL = "OPEN_TASK_RESTORE_MODAL";
const CLOSE_TASK_RESTORE_MODAL = "CLOSE_TASK_RESTORE_MODAL";
const SET_CUSTOM_FIELD_CREATOR_MODAL_OPEN =
  "SET_CUSTOM_FIELD_CREATOR_MODAL_OPEN";
const SET_CUSTOM_FIELD_RECOVERY_MODAL_OPEN =
  "SET_CUSTOM_FIELD_RECOVERY_MODAL_OPEN";

//Archive reducer constants
const SET_ARCHIVE_TASKS = "SET_ARCHIVE_TASKS";
const OPEN_ARCHIVE_TASK_MODAL = "OPEN_ARCHIVE_TASK_MODAL";
const CLOSE_ARCHIVE_TASK_MODAL = "CLOSE_ARCHIVE_TASK_MODAL";
const SET_ARCHIVE_SEARCH_VALUE = "SET_ARCHIVE_SEARCH_VALUE";
const SET_ARCHIVE_FILTERED_PIPELINE = "SET_ARCHIVE_FILTERED_PIPELINE";
const REMOVE_ARCHIVED_TASK = "REMOVE_ARCHIVED_TASK";
const REMOVE_ARCHIVED_TASKS = "REMOVE_ARCHIVED_TASKS";
const ADD_ASSIGNED_USER_TO_ARCHIVED_TASK = "ADD_ASSIGNED_USER_TO_ARCHIVED_TASK";
const REMOVE_ASSINGED_USER_FROM_ARCHIVED_TASK =
  "REMOVE_ASSINGED_USER_FROM_ARCHIVED_TASK";
const CHANGE_ARCHIVED_TASK_DONE_STATUS = "CHANGE_ARCHIVED_TASK_DONE_STATUS";
const EDIT_ARCHIVED_TASK = "EDIT_ARCHIVED_TASK";
const CHANGE_ARCHIVE_TASK_DONE_FILTER = "CHANGE_ARCHIVE_TASK_DONE_FILTER";
const ADD_LABEL_ARCHIVED_TASK = "ADD_LABEL_ARCHIVED_TASK";
const REMOVE_LABEL_ARCHIVED_TASK = "REMOVE_LABEL_ARCHIVED_TASK";
const CHANGE_ARCHIVED_TASKS_LIMIT_FILTER = "CHANGE_ARCHIVED_TASKS_LIMIT_FILTER";
const SET_ARCHIVE_LOADING = "SET_ARCHIVE_LOADING";
const SET_ARCHIVE_FILTER_ORDER = "SET_ARCHIVE_FILTER_ORDER";

//User reducer constants
const SET_USERS = "SET_USERS";
const SET_WP_USERS = "SET_WP_USERS";
const ADD_USER = "ADD_USER";
const SET_USERS_SEARCH_VALUE = "SET_USERS_SEARCH_VALUE";
const EDIT_USER = "EDIT_USER";
const DELETE_USER = "DELETE_USER";
const CHANGE_USER_STATUS = "CHANGE_USER_STATUS";
const RESET_PASSWORD = "RESET_PASSWORD";

//App reducer
const SET_SITE_URL = "SET_SITE_URL";
const INIT_APP_STATE = "INIT_APP_STATE";
const SET_CUSTOM_USER_PAGE_STYLES = "SET_CUSTOM_USER_PAGE_STYLES";

//Loading reducer
const SET_FULL_PAGE_LOADING = "SET_FULL_PAGE_LOADING";

//User sessions reducer
const SET_USER_SESSIONS_SEARCH_VALUE = "SET_USER_SESSIONS_SEARCH_VALUE";
const SET_USER_SESSIONS = "SET_USER_SESSIONS";
const CHANGE_USER_SESSION_STATUS = "CHANGE_USER_SESSION_STATUS";
const DELETE_USER_SESSION = "DELETE_USER_SESSION";

//User tasks reducer
const SET_USER_TASKS = "SET_USER_TASKS";
const SET_USER_TASKS_SEARCH_VALUE = "SET_USER_TASKS_SEARCH_VALUE";
const REMOVE_USER_TASK = "REMOVE_USER_TASK";
const EDIT_USER_TASK = "EDIT_USER_TASK";
const SET_USER_TASKS_FILTERED_PIPELINE = "SET_USER_TASKS_FILTERED_PIPELINE";
const ADD_ASSIGNED_USER_TO_USER_TASK = "ADD_ASSIGNED_USER_TO_USER_TASK";
const REMOVE_ASSIGNED_USER_FROM_USER_TASK =
  "REMOVE_ASSIGNED_USER_FROM_USER_TASK";
const CHANGE_USER_TASK_DONE_STATUS = "CHANGE_USER_TASK_DONE_STATUS";

//Custom Fields reducer
const SET_CUSTOM_FIELDS = "SET_CUSTOM_FIELDS";
const ADD_CUSTOM_FIELD = "ADD_CUSTOM_FIELD";
const EDIT_CUSTOM_FIELD = "EDIT_CUSTOM_FIELD";
const DELETE_CUSTOM_FIELD = "DELETE_CUSTOM_FIELD";
const SET_CUSTOM_FIELD_LOADING = "SET_CUSTOM_FIELD_LOADING";
const SET_CUSTOM_FIELDS_LOCATION = "SET_CUSTOM_FIELDS_LOCATION";
const SET_CUSTOM_FIELD_INITIAL_DATA = "SET_CUSTOM_FIELD_INITIAL_DATA";

//Labels reducer
const SET_LABELS = "SET_LABELS";
const ADD_LABEL = "ADD_LABEL";
const REMOVE_LABEL = "REMOVE_LABEL";
const EDIT_LABEL = "EDIT_LABEL";
const SET_LABEL_ACTION_STATE_SELECTION = "SET_LABEL_ACTION_STATE_SELECTION";
const SET_LABEL_ACTION_STATE_EDITING = "SET_LABEL_ACTION_STATE_EDITING";
const SET_LABEL_ACTION_STATE_CREATION = "SET_LABEL_ACTION_STATE_CREATION";
const RESET_LABEL_CONTEXT = "RESET_LABEL_CONTEXT";

//Pipeline automations reducer
const SET_PIPELINE_AUTOMATIONS = "SET_PIPELINE_AUTOMATIONS";
const SET_PIPELINE_AUTOMATIONS_LOADING = "SET_PIPELINE_AUTOMATIONS_LOADING";
const REMOVE_PIPELINE_AUTOMATION = "REMOVE_PIPELINE_AUTOMATION";
const ADD_PIPELINE_AUTOMATION = "ADD_PIPELINE_AUTOMATION";
const UPDATE_PIPELINE_AUTOMATION_ACTIVE_STATUS =
  "UPDATE_PIPELINE_AUTOMATION_ACTIVE_STATUS";

//Pipeline automation creeation reducer
const SET_AUTOMATION_META = "SET_META";
const SET_AUTOMATION_ACTION_TARGET = "SET_ACTION_TARGET";
const RESET_AUTOMATION_TO_TARGET = "RESET_AUTOMATION_TO_TARGET";
const RESET_AUTOMATION_TO_TRIGGER = "RESET_AUTOMATION_TO_TRIGGER";
const RESET_AUTOMATION_TO_ACTION = "RESET_AUTOMATION_TO_ACTION";

//Pipeline webhooks reducer
const SET_PIPELINE_WEBHOOKS = "SET_PIPELINE_WEBHOOKS";
const SET_PIPELINE_WEBHOOKS_LOADING = "SET_PIPELINE_WEBHOOKS_LOADING";
const REMOVE_PIPELINE_WEBHOOK = "REMOVE_PIPELINE_WEBHOOK";
const ADD_PIPELINE_WEBHOOK = "ADD_PIPELINE_WEBHOOK";
const UPDATE_PIPELINE_WEBHOOK_ACTIVE_STATUS =
  "UPDATE_PIPELINE_WEBHOOK_ACTIVE_STATUS";

//Upload reducer constants
const SET_UPLOADS = "SET_UPLOADS";
const ADD_UPLOAD = "ADD_UPLOAD";
const REMOVE_UPLOAD = "REMOVE_UPLOAD";

//Timers
const REFETCH_ACTIVE_PIPELINE_INTERVAL = 30000;
const TEXT_ENTER_DEBOUNCE_TIMEOUT = 700;

//Misc
const WP_QUICKTASKER_INVALID_SESSION_TOKEN = "Invalid session token";
const HAS_AUTOMATIONS = false;
const DATETIME_FORMAT = "YYYY-MM-DD HH:mm:ss";

//Styles
const DEFAULT_TASK_FOCUS_COLOR = "#ffffff";
const TASK_FOCUS_BORDER_WIDTH = "6px";
const TASK_FOCUS_BORDER_STYLE = "solid";
const DEFAULT_IMPORT_LABEL_COLOR = "#16a34a";

//Validation
const ALLOWED_UPLOAD_FILE_TYPES = [
  "application/pdf",
  "application/msword",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "application/vnd.ms-excel",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  "text/csv",
  "text/plain",
  "image/jpeg",
  "image/png",
  "image/gif",
  "image/bmp",
  "image/svg+xml",
  "audio/mpeg",
  "audio/wav",
  "audio/ogg",
  "video/mp4",
  "video/webm",
  "video/ogg",
  "application/zip",
  "application/x-rar-compressed",
  "application/x-tar",
  "application/gzip",
];
const MAX_UPLOAD_FILE_SIZE = 25 * 1024 * 1024; // 25 MB
const FILE_NAME_REGEX = /^[a-zA-Z0-9_\-.]+$/;

export {
  ADD_ASSIGNED_USER_TO_ARCHIVED_TASK,
  ADD_ASSIGNED_USER_TO_EDITING_TASK,
  ADD_ASSIGNED_USER_TO_USER_TASK,
  ADD_CUSTOM_FIELD,
  ADD_LABEL,
  ADD_LABEL_ARCHIVED_TASK,
  ADD_PIPELINE_AUTOMATION,
  ADD_PIPELINE_WEBHOOK,
  ADD_UPLOAD,
  ADD_USER,
  ALLOWED_UPLOAD_FILE_TYPES,
  ARCHIVE_SETTINGS_MODAL_OPEN,
  CHANGE_ARCHIVED_TASKS_LIMIT_FILTER,
  CHANGE_ARCHIVED_TASK_DONE_STATUS,
  CHANGE_ARCHIVE_TASK_DONE_FILTER,
  CHANGE_TASK_DONE_STATUS,
  CHANGE_TASK_EXPORT_MODAL_METHOD,
  CHANGE_USER_SESSION_STATUS,
  CHANGE_USER_SETTINGS_MODAL_OPEN,
  CHANGE_USER_STATUS,
  CHANGE_USER_TASK_DONE_STATUS,
  CLOSE_ARCHIVE_TASK_MODAL,
  CLOSE_AUTOMATIONS_MODAL,
  CLOSE_AUTOMATION_CREATOR_MODAL,
  CLOSE_EDIT_TASK_MODAL,
  CLOSE_MOVE_TASK_MODAL,
  CLOSE_NEW_TASK_MODAL,
  CLOSE_PIPELINE_IMPORT_MODAL,
  CLOSE_PIPELINE_MODAL,
  CLOSE_STAGE_MODAL,
  CLOSE_TASK_COLOR_MODAL,
  CLOSE_TASK_EXPORT_MODAL,
  CLOSE_TASK_MODAL,
  CLOSE_TASK_RESTORE_MODAL,
  CLOSE_USER_MODAL,
  DATETIME_FORMAT,
  DEFAULT_IMPORT_LABEL_COLOR,
  DEFAULT_TASK_FOCUS_COLOR,
  DELETE_CUSTOM_FIELD,
  DELETE_USER,
  DELETE_USER_SESSION,
  EDIT_ARCHIVED_TASK,
  EDIT_CUSTOM_FIELD,
  EDIT_LABEL,
  EDIT_USER,
  EDIT_USER_TASK,
  FILE_NAME_REGEX,
  HAS_AUTOMATIONS,
  INIT_APP_STATE,
  MAX_UPLOAD_FILE_SIZE,
  OPEN_ARCHIVE_TASK_MODAL,
  OPEN_AUTOMATIONS_MODAL,
  OPEN_AUTOMATION_CREATOR_MODAL,
  OPEN_EDIT_PIPELINE_MODAL,
  OPEN_EDIT_TASK_MODAL,
  OPEN_EDIT_USER_MODAL,
  OPEN_MOVE_TASK_MODAL,
  OPEN_NEW_PIPELINE_MODAL,
  OPEN_NEW_STAGE_MODAL,
  OPEN_NEW_TASK_MODAL,
  OPEN_NEW_USER_MODAL,
  OPEN_PIPELINE_IMPORT_MODAL,
  OPEN_STAGE_EDIT_MODAL,
  OPEN_TASK_COLOR_MODAL,
  OPEN_TASK_EXPORT_MODAL,
  OPEN_TASK_RESTORE_MODAL,
  PIPELINES_SET,
  PIPELINE_ADD_EXISTING_PIPELINE,
  PIPELINE_ADD_LABEL_TO_TASK,
  PIPELINE_ADD_PIPELINE,
  PIPELINE_ADD_STAGE,
  PIPELINE_ADD_TASK,
  PIPELINE_ADD_USER_TO_TASK,
  PIPELINE_CHANGE_TASK_DONE_STATUS,
  PIPELINE_DELETE_STAGE,
  PIPELINE_EDIT_LABEL,
  PIPELINE_EDIT_PIPELINE,
  PIPELINE_EDIT_STAGE,
  PIPELINE_EDIT_TASK,
  PIPELINE_MOVE_STAGE,
  PIPELINE_MOVE_TASK,
  PIPELINE_REMOVE_ACTIVE_PIPELINE,
  PIPELINE_REMOVE_LABEL,
  PIPELINE_REMOVE_LABEL_FROM_TASK,
  PIPELINE_REMOVE_PIPELINE,
  PIPELINE_REMOVE_TASK,
  PIPELINE_REMOVE_USER_FROM_TASK,
  PIPELINE_REORDER_TASK,
  PIPELINE_SET_EXISTING_PIPELINES,
  PIPELINE_SET_LOADING,
  PIPELINE_SET_PIPELINE,
  PIPELINE_SET_PRIMARY,
  PIPELINE_SET_PRIMARY2,
  PIPELINE_SET_TASK_FOCUS_COLOR,
  PIPELINE_TOGGLE_VIEW,
  REFETCH_ACTIVE_PIPELINE_INTERVAL,
  REMOVE_ARCHIVED_TASK,
  REMOVE_ARCHIVED_TASKS,
  REMOVE_ASSIGNED_USER_FROM_EDITING_TASK,
  REMOVE_ASSIGNED_USER_FROM_USER_TASK,
  REMOVE_ASSINGED_USER_FROM_ARCHIVED_TASK,
  REMOVE_LABEL,
  REMOVE_LABEL_ARCHIVED_TASK,
  REMOVE_PIPELINE_AUTOMATION,
  REMOVE_PIPELINE_WEBHOOK,
  REMOVE_UPLOAD,
  REMOVE_USER_TASK,
  RESET_AUTOMATION_TO_ACTION,
  RESET_AUTOMATION_TO_TARGET,
  RESET_AUTOMATION_TO_TRIGGER,
  RESET_LABEL_CONTEXT,
  RESET_PASSWORD,
  SET_ARCHIVE_FILTERED_PIPELINE,
  SET_ARCHIVE_FILTER_ORDER,
  SET_ARCHIVE_LOADING,
  SET_ARCHIVE_SEARCH_VALUE,
  SET_ARCHIVE_TASKS,
  SET_AUTOMATION_ACTION_TARGET,
  SET_AUTOMATION_META,
  SET_CUSTOM_FIELDS,
  SET_CUSTOM_FIELDS_LOCATION,
  SET_CUSTOM_FIELD_CREATOR_MODAL_OPEN,
  SET_CUSTOM_FIELD_INITIAL_DATA,
  SET_CUSTOM_FIELD_LOADING,
  SET_CUSTOM_FIELD_RECOVERY_MODAL_OPEN,
  SET_CUSTOM_USER_PAGE_STYLES,
  SET_FULL_PAGE_LOADING,
  SET_LABELS,
  SET_LABEL_ACTION_STATE_CREATION,
  SET_LABEL_ACTION_STATE_EDITING,
  SET_LABEL_ACTION_STATE_SELECTION,
  SET_PIPELINE_AUTOMATIONS,
  SET_PIPELINE_AUTOMATIONS_LOADING,
  SET_PIPELINE_WEBHOOKS,
  SET_PIPELINE_WEBHOOKS_LOADING,
  SET_SITE_URL,
  SET_STAGE_FILTER,
  SET_TASK_VIEW_SEARCH_TEXT,
  SET_UPLOADS,
  SET_USERS,
  SET_USERS_SEARCH_VALUE,
  SET_USER_FILTER,
  SET_USER_SESSIONS,
  SET_USER_SESSIONS_SEARCH_VALUE,
  SET_USER_TASKS,
  SET_USER_TASKS_FILTERED_PIPELINE,
  SET_USER_TASKS_SEARCH_VALUE,
  SET_WP_USERS,
  TASK_FOCUS_BORDER_STYLE,
  TASK_FOCUS_BORDER_WIDTH,
  TEXT_ENTER_DEBOUNCE_TIMEOUT,
  UPDATE_PIPELINE_AUTOMATION_ACTIVE_STATUS,
  UPDATE_PIPELINE_WEBHOOK_ACTIVE_STATUS,
  WP_QUICKTASKER_INVALID_SESSION_TOKEN,
};
