//Pipeline reducer constants
const PIPELINE_SET_LOADING = "SET_LOADING";
const PIPELINE_SET_PIPELINE = "SET_PIPELINE";
const PIPELINE_MOVE_TASK = "MOVE_TASK";
const PIPELINE_REORDER_TASK = "REORDER_TASK";
const PIPELINE_ADD_TASK = "ADD_TASK";
const PIPELINE_ADD_STAGE = "ADD_STAGE";
const PIPELINE_DELETE_STAGE = "DELETE_STAGE";
const PIPELINE_SET_EXISTING_PIPELINES = "SET_EXISTING_PIPELINES";
const PIPELINE_ADD_EXISTING_PIPELINE = "ADD_EXISTING_PIPELINE";
const PIPELINE_EDIT_TASK = "EDIT_TASK";
const PIPELINE_EDIT_STAGE = "EDIT_STAGE";
const PIPELINE_MOVE_STAGE = "MOVE_STAGE";
const PIPELINE_ADD_PIPELINE = "ADD_PIPELINE";
const PIPELINE_EDIT_PIPELINE = "EDIT_PIPELINE";
const PIPELINE_SET_PRIMARY = "SET_PRIMARY";

//Modal reducer constants
const OPEN_NEW_TASK_MODAL = "OPEN_NEW_TASK_MODAL";
const CLOSE_NEW_TASK_MODAL = "CLOSE_NEW_TASK_MODAL";
const OPEN_EDIT_TASK_MODAL = "OPEN_EDIT_TASK_MODAL";
const CLOSE_EDIT_TASK_MODAL = "CLOSE_EDIT_TASK_MODAL";
const CLOSE_TASK_MODAL = "CLOSE_TASK_MODAL";
const OPEN_NEW_STAGE_MODAL = "OPEN_NEW_STAGE_MODAL";
const CLOSE_STAGE_MODAL = "CLOSE_STAGE_MODAL";
const OPEN_STAGE_EDIT_MODAL = "OPEN_STAGE_EDIT_MODAL";
const OPEN_NEW_PIPELINE_MODAL = "OPEN_NEW_PIPELINE_MODAL";
const OPEN_EDIT_PIPELINE_MODAL = "OPEN_EDIT_PIPELINE_MODAL";
const CLOSE_PIPELINE_MODAL = "CLOSE_PIPELINE_EDIT_MODAL";

//Archive reducer constants
const SET_ARCHIVE_TASKS = "SET_ARCHIVE_TASKS";
const OPEN_ARCHIVE_TASK_MODAL = "OPEN_ARCHIVE_TASK_MODAL";
const CLOSE_ARCHIVE_TASK_MODAL = "CLOSE_ARCHIVE_TASK_MODAL";

export {
  PIPELINE_SET_LOADING,
  PIPELINE_SET_PIPELINE,
  PIPELINE_MOVE_TASK,
  PIPELINE_REORDER_TASK,
  PIPELINE_ADD_TASK,
  PIPELINE_ADD_STAGE,
  PIPELINE_DELETE_STAGE,
  PIPELINE_SET_EXISTING_PIPELINES,
  PIPELINE_ADD_EXISTING_PIPELINE,
  PIPELINE_ADD_PIPELINE,
  OPEN_NEW_TASK_MODAL,
  CLOSE_NEW_TASK_MODAL,
  OPEN_EDIT_TASK_MODAL,
  CLOSE_EDIT_TASK_MODAL,
  CLOSE_TASK_MODAL,
  PIPELINE_EDIT_TASK,
  OPEN_NEW_STAGE_MODAL,
  CLOSE_STAGE_MODAL,
  OPEN_STAGE_EDIT_MODAL,
  PIPELINE_EDIT_STAGE,
  PIPELINE_MOVE_STAGE,
  OPEN_NEW_PIPELINE_MODAL,
  OPEN_EDIT_PIPELINE_MODAL,
  CLOSE_PIPELINE_MODAL,
  PIPELINE_EDIT_PIPELINE,
  PIPELINE_SET_PRIMARY,
  SET_ARCHIVE_TASKS,
  OPEN_ARCHIVE_TASK_MODAL,
  CLOSE_ARCHIVE_TASK_MODAL,
};
