<?php
namespace WPQT\Export;

if ( ! defined( 'ABSPATH' ) ) {
	exit; 
}

use WPWT\ServiceLocator;
use WPQT\Export;

require_once( WP_QUICKTASKER_PLUGIN_FOLDER_DIR . 'php/libs/tfpdf/tfpdf.php' );

if ( ! class_exists( 'PDFExportService' ) ) {
    class PDFExportService extends ExportService {
        private $_pdf = null;

        public function __construct($pipelineId) {
            parent::__construct($pipelineId);
            $this->setUpPdf();
        }

        private function setUpPdf() {
            $this->_pdf = new \TFPDF();
            $this->_pdf->SetTitle( $this->getFileName() );
            $this->_pdf->SetAuthor('QuickTasker WordPress');
            $this->_pdf->AddFont('DejaVu','','DejaVuSans.ttf', true);
            $this->_pdf->AliasNbPages();
            $this->_pdf->AddPage();
            $this->_pdf->SetFont('DejaVu','',10);
        }

        public function generateTasksPdfExport() {
            $this->_pdf->Cell(0, 10, 'This is a test PDF generated by QuickTasker.', 0, 1);
            $this->_pdf->Cell(0, 10, 'Pipeline ID: ' . $this->_pipelineId, 0, 1);
            $this->_pdf->Cell(0, 10, 'Generated at: ' . date('Y-m-d H:i:s'), 0, 1);

            $this->_pdf->Output('F', WP_QUICKTASKER_TASK_EXPORTS_FOLDER_DIR . '/' . $this->_fileName . '.pdf');    
            
            return (object)[
                'file_name' => $this->_fileName . '.pdf',
                'file_path' => WP_QUICKTASKER_TASK_EXPORTS_FOLDER_DIR . '/' . $this->_fileName . '.pdf',
                'file_url' => WP_QUICKTASKER_TASK_EXPORTS_FOLDER_URL . '/' . $this->_fileName . '.pdf'
            ];
        }
    }
}